version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - php-fpm
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8090:80
        links:
            - db:db
    php-fpm:
        build:
            context: ./docker
            dockerfile: php.docker
        volumes:
            - ./:/var/www
        depends_on:
            - db
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
            - "MYSQL_DATABASE=notestore"