version: '3'
services:
    nginx:
        image: nginx:1.10
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php-fpm
    #phpmyadmin:
        #image: phpmyadmin/phpmyadmin
        #ports:
            #- 8090:80
        #links:
            #- mysql:db
    php-fpm:
        build:
            context: ./docker
            dockerfile: php.docker
        volumes:
            - ./:/var/www
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - db
            - redis
            #- mysql
    #mysql:
        #image: mysql:latest
        #command: --default-authentication-plugin=mysql_native_password
        #restart: always
        #volumes:
            #- ./storage/docker/mysql:/var/lib/mysql
        #environment:
            #- "MYSQL_ROOT_PASSWORD=password"
            #- "MYSQL_DATABASE=notestore"
    db:
        image: postgres:latest
        volumes:
            - ./storage/docker/postgresql:/var/lib/postgresql/data
        environment:
            - "POSTGRES_USER=root"
            - "POSTGRES_PASSWORD=password"
            - "POSTGRES_DB=notestore"
    adminer:
        image: adminer
        restart: always
        ports:
            - 8092:8080
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./storage/docker/redis:/data
        restart: always